- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: create directory and unzip the content
  include_tasks: unzip.yml

- name: copy and start the service
  include_tasks: systemD.yml