- name: Install nodejs
  apt:
    name: nodejs
    update_cache: yes
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: Create a directory
  file:
    path: /root/{{COMPONENT}}
    state: directory

- name: unzip the downloaded content
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /root/{{COMPONENT}}
    remote_src: yes

- name: copy and start the service
  include_tasks: systemD.yml