- name: Install Nginx
  apt:
    name: nginx
    update_cache: yes
    state: present

- name: Install nodejs
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Removing default files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/nginx/sites-available/default
    - /etc/nginx/sites-enabled/default
    - /var/www/html/index.nginx-debian.html

- name: create a vue directory
  file:
    path: /var/www/html/vue
    state: directory

- name: create {{COMPONENT}} directory
  file:
    path: /var/www/html/vue/{{COMPONENT}}
    state: directory

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: unzip the downloaded content
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /var/www/html/vue/{{COMPONENT}}
    remote_src: yes

- name: Update Todo config file
  template:
    src: default.config
    dest: /etc/nginx/sites-enabled/default.config
  notify: Restart Nginx

- name: Start service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Import node_exporter from common
  include_role:
    name: common
    tasks_from: node_exporter.yml