- name: Import Java from common role
  include_role:
    name: common
    tasks_from: java.yml

- name: Import node_exporter from common
  include_role:
    name: common
    tasks_from: node_exporter.yml

- name: Import filebeat common role
  include_role:
    name: common
    tasks_from: filebeat
  vars:
    IS_STRUCTURED: false
    LOG_FILES:
      - { file: "/var/log/{{COMPONENT}}.log", type: "{{COMPONENT}}" }