- name: Install openjdk
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Download Artifacts from Nexus
  get_url:
    url: http://34.201.27.100:8081/repository/users/users-{{APP_VERSION}}.zip
    dest: /tmp/users.zip
    username: admin
    password: Omkar@123

- name: Create a directory
  file:
    path: /root/users
    state: directory

- name: unzip the downloaded content
  unarchive:
    src: /tmp/users.zip
    dest: /root/users
    remote_src: yes

- name: copy the service file
  template:
    src: "users.service"
    dest: /etc/systemd/system/users.service

- name: Start service
  systemd:
    name: users
    daemon_reload: yes
    state: started
    enabled: yes

