- name: Install openjdk
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: Create a directory
  file:
    path: /root/users
    state: directory

- name: unzip the downloaded content
  unarchive:
    src: /tmp/users.zip
    dest: /root/users
    remote_src: yes

- name: copy the service file
  template:
    src: "users.service"
    dest: /etc/systemd/system/users.service

- name: Start service
  systemd:
    name: users
    daemon_reload: yes
    state: started
    enabled: yes

