- name: Install openjdk
  apt:
    name: openjdk-8-jdk-headless
    update_cache: yes
    state: present

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: create directory and unzip the content
  include_role:
    name: common
    tasks_from: unzip.yml

- name: copy and start the service
  include_role:
    name: common
    tasks_from: systemD.yml