- name: Import GO from common role
  include_role:
    name: common
    tasks_from: golang.yml

- name: Import node_exporter from common
  include_role:
    name: common
    tasks_from: node_exporter.yml