- name: Install go-lang
  apt:
    name: golang
    update_cache: yes
    state: present

- name: Create a directory
  file:
    path: /root/go/src/{{COMPONENT}}
    state: directory

- name: Import artifacts
  include_role:
    name: common
    tasks_from: download-artifacts.yml

- name: Unarchive the downloaded content
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /root/go/src/{{COMPONENT}}
    remote_src: yes

- name: copy the service file
  template:
    src: "{{COMPONENT}}.service"
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes