- name: Download Artifacts from Nexus
  get_url:
    url: http://54.160.26.194:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    username: admin
    password: Omkar@123