- name: Install go-lang
  apt:
    name: golang
    update_cache: yes
    state: present

- name: Create a directory
  file:
    path: /root/go/src/{{COMPONENT}}
    state: directory

- name: Import artifacts
  include_tasks: download-artifacts.yml

- name: Unarchive the downloaded content
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /root/go/src/{{COMPONENT}}
    remote_src: yes

- name: copy and start the service
  include_tasks: systemD.yml