- name: Setup hostname
  shell: set-hostname {{COMPONENT}}

- name: Update Rsyslog config
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/default.config

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted